import {
  CREATE_STORE_OWNER_NAME_UNIQUE_INDEX_SQL,
  CREATE_STORE_OWNER_TABLE_SQL,
  CREATE_STORE_OWNER_UPDATED_AT_INDEX_SQL,
} from "@/db/schema";

export const STORE_OWNER_MIGRATION_STATEMENTS = [
  CREATE_STORE_OWNER_TABLE_SQL,
  CREATE_STORE_OWNER_NAME_UNIQUE_INDEX_SQL,
  CREATE_STORE_OWNER_UPDATED_AT_INDEX_SQL,
];
