"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OWNER_SCOPED_ENTITY_MIGRATION_STATEMENTS = void 0;
const schema_1 = require("@/db/schema");
exports.OWNER_SCOPED_ENTITY_MIGRATION_STATEMENTS = [
    schema_1.CREATE_PRODUCT_TABLE_SQL,
    schema_1.CREATE_PRODUCT_OWNER_BARCODE_UNIQUE_INDEX_SQL,
    schema_1.CREATE_PRODUCT_OWNER_CREATED_AT_INDEX_SQL,
    schema_1.CREATE_PRODUCT_OWNER_ID_UNIQUE_INDEX_SQL,
    schema_1.CREATE_SHOPPER_TABLE_SQL,
    schema_1.CREATE_SHOPPER_OWNER_CREATED_AT_INDEX_SQL,
    schema_1.CREATE_SHOPPER_OWNER_PIN_UNIQUE_INDEX_SQL,
    schema_1.CREATE_SHOPPER_OWNER_ID_UNIQUE_INDEX_SQL,
    schema_1.CREATE_SHOPPING_LIST_ITEM_TABLE_SQL,
    schema_1.CREATE_SHOPPING_LIST_ITEM_OWNER_CREATED_AT_INDEX_SQL,
    schema_1.CREATE_PURCHASE_TABLE_SQL,
    schema_1.CREATE_PURCHASE_OWNER_CREATED_AT_INDEX_SQL,
    schema_1.CREATE_PAYMENT_TABLE_SQL,
    schema_1.CREATE_PAYMENT_OWNER_CREATED_AT_INDEX_SQL,
];
